{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "starrupture-dedicated-server.serviceAccountName" . }}
  labels:
    {{- include "starrupture-dedicated-server.labels" . | nindent 4 }}
{{- end -}}
