apiVersion: v1
kind: Service
metadata:
  name: {{ include "starrupture-dedicated-server.fullname" . }}
  labels:
    {{- include "starrupture-dedicated-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.tcp }}
      nodePort: {{ .Values.service.nodePorts.tcp }}
      {{- end }}
    - name: udp
      port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.udp }}
      nodePort: {{ .Values.service.nodePorts.udp }}
      {{- end }}
  selector:
    {{- include "starrupture-dedicated-server.selectorLabels" . | nindent 4 }}
